"""Synthesis — build the canonical AGENTS.md from what actually recurs.

A rule earns a place in the house standard by appearing in several independent
scopes. For each qualifying topic the generator picks the best *existing*
sentence rather than inventing one: it prefers wording that is binding, concise,
already repeated verbatim elsewhere, and free of project-specific detail.

Fully deterministic. The optional semantic pass can rewrite the chosen lines
afterwards, but the selection and the counts come from here.
"""

from __future__ import annotations

import re
from collections import Counter, defaultdict
from typing import Any

from .parse import IMPERATIVE_START
from .stats import Survey
from .taxonomy import GROUPS, TOPIC_BY_ID, classify, match_strength

# A directive mentioning any of these is talking about one project, not about
# how work is done in general, and must not be lifted into a shared template.
SPECIFIC = re.compile(
    r"(\b[a-z0-9_]+\.(py|cpp|h|hpp|md|json|yaml|yml|toml|dart|rs|kt|java|sh)\b"
    r"|\bsrc/|\btests?/|\bdocs?/|\bbuild/|§\d+|\bv?\d+\.\d+\.\d+\b|https?://"
    r"|python -m |npm run|\./[a-z]|\s--[a-z]{2,})",
    re.IGNORECASE,
)

# A sentence ending on one of these was cut off by the segmenter and must not
# be quoted as a rule.
DANGLING = re.compile(
    r"\b(and|or|but|unless|because|that|which|where|with|for|to|if|when|while|"
    r"the|a|an|of|in|on|as|by|from|is|are|into|via|per|plus|than|then|such)[.,]?$",
    re.IGNORECASE,
)

# Ordering of the generated document: the sections a reader needs first.
SECTION_ORDER = (
    "Working process",
    "Commits",
    "Version control",
    "Versioning",
    "Quality gate",
    "Dependencies",
    "Code",
    "Language and voice",
    "Documentation",
    "Safety and privacy",
    "Toolchain",
    "Repository",
)

HEADER = """# AGENTS.md — house standard

Generated by AgentsMdSurvey from {scopes} instructed scopes under `{root}`.
Every rule below was already in use; the count in each comment is the number of
independent scopes that stated it. Rules used in fewer than {threshold} scopes
were left out on purpose — they are project-specific and belong in the project.

Treat this as the starting point for a new repository, then add what only that
repository needs.
"""

FOOTER = """
## What this file deliberately does not contain

Project description, repository layout and command cheat-sheets. In the surveyed
corpus those made up {other_share:.0%} of all sections, and they are the reason
instruction files cannot simply be copied between repositories. Write them per
project, below this line.
"""


def _score(topic: str, repeat_scopes: int, hardness: str, normalized: str) -> tuple:
    """Ranking key for candidate wordings. Higher is better.

    Match strength leads: a sentence that states this topic in several of its
    own words beats one that merely brushes against it, however often that
    other sentence was copied around.
    """
    competing = len(classify(normalized))
    return (
        match_strength(topic, normalized),
        -competing,
        repeat_scopes,  # already copied by hand into several repos
        hardness == "hard",  # binding wording beats advisory
        -abs(len(normalized.split()) - 12),  # around a dozen words reads best
        -len(normalized),
    )


def _usable(directive, topic: str) -> bool:
    """Whether this directive may represent this topic in a shared file.

    The directive has to *state* the topic in its own words — a topic inherited
    from the heading path is good enough to count, but not to quote. It also has
    to be generic: anything naming a file, a path, a version or a URL describes
    one project and would be a lie in the next one.
    """
    if not 4 <= directive.words <= 40:
        return False
    if topic not in classify(directive.normalized):
        return False
    if SPECIFIC.search(directive.normalized):
        return False
    if directive.normalized.startswith(("[", "e.g", "for example")):
        return False
    if DANGLING.search(directive.normalized):
        return False
    return True


def choose_rules(survey: Survey, min_scopes: int) -> dict[str, list[dict[str, Any]]]:
    """One representative wording per qualifying topic, grouped by taxonomy group."""
    topic_scopes = survey.topic_scopes()
    repeat_counts: Counter[str] = Counter()
    fingerprint_scopes: dict[str, set[str]] = defaultdict(set)
    candidates: dict[str, list[tuple[Any, dict[str, Any]]]] = defaultdict(list)

    for item, directive in survey.directives():
        fingerprint_scopes[directive.fingerprint].add(item.scope)
    for item, directive in survey.directives():
        repeats = len(fingerprint_scopes[directive.fingerprint])
        for topic in directive.topics:
            if len(topic_scopes.get(topic, ())) < min_scopes:
                continue
            if not _usable(directive, topic):
                continue
            candidates[topic].append(
                (
                    _score(topic, repeats, directive.hardness, directive.normalized),
                    directive.fingerprint,
                    {
                        "text": directive.text.rstrip(),
                        "scope": item.scope,
                        "file": item.rel_path,
                        "line": directive.line,
                        "repeats": repeats,
                    },
                )
            )
        repeat_counts[directive.fingerprint] = repeats

    # One sentence may be the best fit for two topics. Award it to the topic
    # with the broader support and let the runner-up take the next wording, so
    # the generated file never repeats itself.
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    taken: set[str] = set()
    for topic in sorted(candidates, key=lambda t: (-len(topic_scopes[t]), t)):
        options = sorted(candidates[topic], key=lambda row: row[0], reverse=True)
        chosen = next((row for row in options if row[1] not in taken), None)
        if chosen is None:
            continue
        taken.add(chosen[1])
        meta = TOPIC_BY_ID[topic]
        grouped[meta.group].append(
            {
                "topic": topic,
                "label": meta.label,
                "scopes": len(topic_scopes[topic]),
                "scope_names": sorted(topic_scopes[topic]),
                "rule": chosen[2],
            }
        )
    for group in grouped.values():
        group.sort(key=lambda row: (-row["scopes"], row["label"]))
    return grouped


def render(survey: Survey, min_scopes: int) -> str:
    """The canonical AGENTS.md as markdown."""
    grouped = choose_rules(survey, min_scopes)
    total_scopes = len(survey.scopes())

    roles: Counter[str] = Counter()
    for item in survey.first_party:
        doc = survey.parsed.get(item.path)
        if doc is None:
            continue
        for section in doc.sections:
            roles[section.role] += 1
    total_sections = sum(roles.values()) or 1
    other_share = (total_sections - roles.get("rules", 0)) / total_sections

    lines = [HEADER.format(scopes=total_scopes, root=survey.root, threshold=min_scopes)]

    order = [g for g in SECTION_ORDER if g in grouped] + [g for g in GROUPS if g in grouped and g not in SECTION_ORDER]
    for group in order:
        rows = grouped[group]
        lines.append(f"## {group}\n")
        for row in rows:
            rule = row["rule"]
            text = rule["text"]
            if not text.endswith((".", "!", "?", ":")):
                text += "."
            lines.append(f"- {text}")
            provenance = f"{row['scopes']}/{total_scopes} scopes"
            if rule["repeats"] > 1:
                provenance += f", this wording verbatim in {rule['repeats']}"
            lines.append(f"  <!-- {row['label']} — {provenance}; from {rule['file']}:{rule['line']} -->")
        lines.append("")

    lines.append(FOOTER.format(other_share=other_share))
    return "\n".join(lines)
