/* SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (C) 2026 Marcel Petrick <mail@marcelpetrick.it>
 */
/* ESE Kongress 2026 -- local schedule viewer.
 *
 * Everything runs offline from window.CONGRESS_DATA (web/data.js, generated by
 * crawler/parse.py). No fetch(), no build step, so the page works when it is
 * opened straight from the file system.
 *
 *   hover an event  -> detail popup with the full abstract
 *   click an event  -> mark / unmark it (kept in localStorage)
 *   chips           -> highlight project management, team leadership,
 *                      agentic AI and scaling content
 */
'use strict';

const DATA = window.CONGRESS_DATA;
const TAG_ORDER = ['project-management', 'team-management', 'agentic-ai', 'scaling'];
const TAG_SHORT = {
  'project-management': 'Projekt',
  'team-management': 'Team',
  'agentic-ai': 'Agentic AI',
  'scaling': 'Skalierung',
};
const FIELD_LABEL = { topic: 'Thema', title: 'Titel', subtitle: 'Untertitel', abstract: 'Abstract' };

const PX_PER_MIN = 1.6;
const TICK_MINUTES = 30;
const MIN_CARD_HEIGHT = 22;

const MARKS_KEY = 'ese2026.marks';
const STATE_KEY = 'ese2026.state';

const byUid = new Map(DATA.events.map((event) => [event.uid, event]));

/* ------------------------------------------------------------------ state */
const marks = new Set(load(MARKS_KEY, []));

const state = Object.assign({
  day: DATA.days.find((day) => day.event_uids.length > 2)?.id || DATA.days[0].id,
  view: 'grid',
  query: '',
  topic: '',
  tags: [],
  onlyHits: false,
  onlyMarked: false,
  includeWeak: false,
}, load(STATE_KEY, {}));

function load(key, fallback) {
  try {
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : fallback;
  } catch (error) {
    console.warn('localStorage unavailable:', error);
    return fallback;
  }
}

function save(key, value) {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch (error) {
    console.warn('could not persist', key, error);
  }
}

const persistMarks = () => save(MARKS_KEY, [...marks]);
const persistState = () => save(STATE_KEY, state);

/* ------------------------------------------------------------- filtering */
function activeTagsOf(event) {
  const tags = state.includeWeak ? event.tags.concat(event.weak_tags) : event.tags;
  return tags;
}

/** Hard filters remove an event from the view, the tag chips only dim it
 *  (unless "nur Treffer" is on) -- that keeps the day's shape recognisable. */
function passesHardFilter(event) {
  if (state.onlyMarked && !marks.has(event.uid)) return false;
  if (state.topic && event.topic !== state.topic) return false;
  if (state.query) {
    const needle = state.query.toLowerCase();
    if (!event.search_text.includes(needle) && !event.title.toLowerCase().includes(needle)) return false;
  }
  return true;
}

function matchesTags(event) {
  if (!state.tags.length) return true;
  return activeTagsOf(event).some((tag) => state.tags.includes(tag));
}

/* ------------------------------------------------------------- rendering */
const $ = (selector) => document.querySelector(selector);
const main = $('#main');
const popup = $('#popup');

function el(tag, className, textContent) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (textContent != null) node.textContent = textContent;
  return node;
}

function eventCard(event) {
  const card = el('a', 'event');
  card.href = 'javascript:void 0';
  card.dataset.uid = event.uid;
  if (event.kind === 'general') card.classList.add('general');
  if (event.topic_color) card.style.setProperty('--topic-color', event.topic_color);

  const strong = event.tags;
  const shown = activeTagsOf(event);
  if (shown.length) {
    card.classList.add('tagged');
    const bar = el('span', 'tagbar');
    shown.forEach((tag) => {
      const stripe = el('i');
      stripe.style.background = `var(--tag-${tag})`;
      if (!strong.includes(tag)) stripe.style.opacity = '.4';
      bar.appendChild(stripe);
    });
    card.appendChild(bar);
  }

  card.appendChild(el('span', 't', event.title));

  const meta = el('span', 'meta');
  meta.textContent = [
    `${event.start}–${event.end}`,
    event.rooms.join(', '),
    event.topic,
  ].filter(Boolean).join(' · ');
  card.appendChild(meta);

  if (shown.length) {
    const badges = el('span', 'badges');
    shown.forEach((tag) => {
      const badge = el('span', strong.includes(tag) ? 'badge' : 'badge weak', TAG_SHORT[tag]);
      badge.style.setProperty('--badge-color', `var(--tag-${tag})`);
      badges.appendChild(badge);
    });
    card.appendChild(badges);
  }

  applyCardState(card, event);
  return card;
}

function applyCardState(card, event) {
  card.classList.toggle('marked', marks.has(event.uid));
  const hit = matchesTags(event);
  card.classList.toggle('dim', !hit && !state.onlyHits);
  card.classList.toggle('hidden', !hit && state.onlyHits);
}

/** Greedy lane assignment so overlapping events in one room sit side by side. */
function assignLanes(events) {
  const lanes = [];
  const placed = new Map();
  events.slice().sort((a, b) => a.start_min - b.start_min || b.end_min - a.end_min)
    .forEach((event) => {
      let lane = lanes.findIndex((end) => end <= event.start_min);
      if (lane === -1) lane = lanes.push(event.start_min) - 1;
      lanes[lane] = event.end_min;
      placed.set(event.uid, lane);
    });
  return { lanes: Math.max(lanes.length, 1), of: placed };
}

function renderGrid(day, events) {
  const wrap = el('div', 'grid-scroll');
  const grid = el('div', 'grid');
  grid.style.gridTemplateColumns = `58px repeat(${day.rooms.length}, minmax(190px, 1fr))`;
  grid.style.setProperty('--tick', `${TICK_MINUTES * PX_PER_MIN}px`);

  const starts = events.map((e) => e.start_min).filter((m) => m != null);
  const ends = events.map((e) => e.end_min).filter((m) => m != null);
  const from = Math.floor(Math.min(...starts) / TICK_MINUTES) * TICK_MINUTES;
  const to = Math.ceil(Math.max(...ends) / TICK_MINUTES) * TICK_MINUTES;
  const height = (to - from) * PX_PER_MIN;

  grid.appendChild(el('div', 'grid-head', ''));
  day.rooms.forEach((room) => grid.appendChild(el('div', 'grid-head', room)));

  const axis = el('div', 'timeaxis');
  axis.style.height = `${height}px`;
  for (let minute = from; minute <= to; minute += TICK_MINUTES) {
    const tick = el('div', 'tick', `${String(Math.floor(minute / 60)).padStart(2, '0')}:${String(minute % 60).padStart(2, '0')}`);
    tick.style.top = `${(minute - from) * PX_PER_MIN}px`;
    axis.appendChild(tick);
  }
  grid.appendChild(axis);

  day.rooms.forEach((room, index) => {
    const column = el('div', 'column');
    column.style.height = `${height}px`;
    const inRoom = events.filter((event) => event.room_index === index);
    const { lanes, of } = assignLanes(inRoom);

    inRoom.forEach((event) => {
      const card = eventCard(event);
      const lane = of.get(event.uid) || 0;
      const width = 100 / lanes;
      card.style.top = `${(event.start_min - from) * PX_PER_MIN + 1}px`;
      card.style.height = `${Math.max((event.end_min - event.start_min) * PX_PER_MIN - 3, MIN_CARD_HEIGHT)}px`;
      card.style.left = `calc(${lane * width}% + 2px)`;
      card.style.width = `calc(${width}% - 4px)`;
      column.appendChild(card);
    });
    grid.appendChild(column);
  });

  wrap.appendChild(grid);
  return wrap;
}

function renderList(events) {
  const list = el('div', 'list');
  let currentDay = null;
  events.slice().sort((a, b) => (a.date.split('.').reverse().join('') + a.start)
    .localeCompare(b.date.split('.').reverse().join('') + b.start))
    .forEach((event) => {
      if (event.day_id !== currentDay) {
        currentDay = event.day_id;
        list.appendChild(el('div', 'list-day', `${event.weekday} ${event.date}`));
      }
      list.appendChild(eventCard(event));
    });
  return list;
}

function render() {
  hidePopup();
  main.textContent = '';

  const day = DATA.days.find((entry) => entry.id === state.day) || DATA.days[0];
  const scope = state.view === 'list' && (state.onlyMarked || state.query)
    ? DATA.events                        /* searching/marked: look across all days */
    : DATA.events.filter((event) => event.day_id === day.id);
  const events = scope.filter(passesHardFilter);

  if (state.view === 'grid') {
    main.appendChild(el('p', 'day-title',
      `${day.weekday}, ${day.date} · ${events.length} Events · ${day.rooms.length} Räume`));
    if (events.length) {
      main.appendChild(renderGrid(day, events));
    } else {
      main.appendChild(el('p', 'hint', 'Keine Events entsprechen den Filtern.'));
    }
  } else {
    const shown = state.onlyHits ? events.filter(matchesTags).length : events.length;
    main.appendChild(el('p', 'day-title',
      state.onlyMarked || state.query
        ? `${shown} Events (alle Tage)`
        : `${day.weekday}, ${day.date} · ${shown} Events`));
    main.appendChild(renderList(events));
  }

  renderChips();
  const visible = main.querySelectorAll('.event:not(.hidden)').length;
  $('#counter').textContent =
    `${visible} sichtbar · ${marks.size} markiert · ${DATA.events.filter((e) => e.tags.length).length} getaggt`;
}

function renderChips() {
  const chips = $('#tag-chips');
  chips.textContent = '';
  TAG_ORDER.forEach((tag) => {
    const strong = DATA.events.filter((event) => event.tags.includes(tag)).length;
    const weak = DATA.events.filter((event) => event.weak_tags.includes(tag)).length;
    const chip = el('button', 'chip' + (state.tags.includes(tag) ? ' on' : ''));
    chip.style.setProperty('--chip-color', `var(--tag-${tag})`);
    chip.appendChild(el('span', 'dot'));
    chip.appendChild(document.createTextNode(DATA.tag_definitions[tag].label));
    chip.appendChild(el('span', 'count', state.includeWeak ? `${strong}+${weak}` : `${strong}`));
    chip.onclick = () => {
      state.tags = state.tags.includes(tag)
        ? state.tags.filter((entry) => entry !== tag)
        : state.tags.concat(tag);
      persistState();
      render();
    };
    chips.appendChild(chip);
  });
}

/* ------------------------------------------------------------------ popup */
let popupTimer = null;
let popupUid = null;

/** The abstracts are raw HTML from the congress site; drop anything active. */
function safeHtml(html) {
  const doc = new DOMParser().parseFromString(`<div>${html}</div>`, 'text/html');
  doc.querySelectorAll('script, style, iframe, object, embed').forEach((node) => node.remove());
  doc.querySelectorAll('*').forEach((node) => {
    [...node.attributes].forEach((attribute) => {
      if (/^on/i.test(attribute.name) || /javascript:/i.test(attribute.value)) {
        node.removeAttribute(attribute.name);
      }
    });
  });
  return doc.body.firstChild.innerHTML;
}

function popupContent(event) {
  const box = document.createDocumentFragment();
  box.appendChild(el('h3', null, event.title));
  box.appendChild(el('p', 'sub',
    `${event.weekday} ${event.date} · ${event.start}–${event.end} Uhr · ${event.rooms.join(', ') || '—'}`));

  const dl = el('dl');
  const row = (label, value) => {
    if (!value) return;
    dl.appendChild(el('dt', null, label));
    dl.appendChild(el('dd', null, value));
  };
  row('Thema', event.topic);
  row('Format', event.form);
  row('Dauer', event.duration);
  row('Leitung', event.direction);
  const speakers = event.papers.flatMap((paper) => paper.persons.map((person) => person.display));
  row('Personen', [...new Set(speakers)].join(' · '));
  box.appendChild(dl);

  const shown = activeTagsOf(event);
  if (shown.length) {
    const why = el('div', 'why');
    why.appendChild(el('b', null, 'Highlight: '));
    shown.forEach((tag, index) => {
      const detail = event.tag_details[tag];
      const strong = event.tags.includes(tag);
      const name = el('span', null,
        `${DATA.tag_definitions[tag].label} (${detail.score}${strong ? '' : ', schwach'})`);
      name.style.color = `var(--tag-${tag})`;
      if (index) why.appendChild(document.createTextNode(' · '));
      why.appendChild(name);
    });
    shown.forEach((tag) => {
      const detail = event.tag_details[tag];
      const parts = Object.entries(detail.matches)
        .map(([field, words]) => `${FIELD_LABEL[field]}: ${words.join(', ')}`);
      const line = el('div');
      line.appendChild(el('code', null, `${TAG_SHORT[tag]} ← ${parts.join(' | ')}`));
      why.appendChild(line);
    });
    box.appendChild(why);
  }

  event.papers.forEach((paper) => {
    const block = el('div', 'paper');
    block.appendChild(el('h4', null, `${paper.time ? paper.time + ' – ' : ''}${paper.title}`));
    if (paper.subtitle) block.appendChild(el('div', 'sub', paper.subtitle));
    if (paper.persons.length) {
      block.appendChild(el('div', 'persons', paper.persons.map((person) => person.display).join(' · ')));
    }
    if (paper.abstract_html) {
      const abstract = el('div', 'abstract');
      abstract.innerHTML = safeHtml(paper.abstract_html);
      block.appendChild(abstract);
    }
    box.appendChild(block);
  });

  if (!event.papers.length) {
    box.appendChild(el('p', 'hint', 'Keine Detailbeschreibung hinterlegt (Pause, Panel oder Rahmenprogramm).'));
  }

  const foot = el('p', 'hint');
  foot.appendChild(document.createTextNode(marks.has(event.uid)
    ? 'Klick entfernt die Markierung · ' : 'Klick markiert dieses Event · '));
  if (event.source_url) {
    const link = el('a', null, 'Original öffnen');
    link.href = event.source_url;
    link.target = '_blank';
    link.rel = 'noopener';
    foot.appendChild(link);
  }
  box.appendChild(foot);
  return box;
}

function showPopup(event, anchor) {
  popupUid = event.uid;
  popup.textContent = '';
  popup.appendChild(popupContent(event));
  popup.hidden = false;

  const rect = anchor.getBoundingClientRect();
  const box = popup.getBoundingClientRect();
  let left = rect.right + 12;
  if (left + box.width > window.innerWidth - 8) left = Math.max(8, rect.left - box.width - 12);
  let top = rect.top;
  if (top + box.height > window.innerHeight - 8) top = Math.max(8, window.innerHeight - box.height - 8);
  popup.style.left = `${left}px`;
  popup.style.top = `${top}px`;
}

function hidePopup() {
  popup.hidden = true;
  popupUid = null;
}

main.addEventListener('mouseover', (domEvent) => {
  const card = domEvent.target.closest('.event');
  if (!card) return;
  const event = byUid.get(card.dataset.uid);
  if (!event || popupUid === event.uid) return;
  clearTimeout(popupTimer);
  popupTimer = setTimeout(() => showPopup(event, card), 90);
});

main.addEventListener('mouseout', (domEvent) => {
  const card = domEvent.target.closest('.event');
  if (!card) return;
  const to = domEvent.relatedTarget;
  if (to && (popup.contains(to) || card.contains(to))) return;
  clearTimeout(popupTimer);
  popupTimer = setTimeout(hidePopup, 220);
});

popup.addEventListener('mouseenter', () => clearTimeout(popupTimer));
popup.addEventListener('mouseleave', () => { popupTimer = setTimeout(hidePopup, 160); });
document.addEventListener('keydown', (domEvent) => { if (domEvent.key === 'Escape') hidePopup(); });

/* ------------------------------------------------------------------ marks */
main.addEventListener('click', (domEvent) => {
  const card = domEvent.target.closest('.event');
  if (!card) return;
  domEvent.preventDefault();
  const event = byUid.get(card.dataset.uid);
  if (marks.has(event.uid)) marks.delete(event.uid); else marks.add(event.uid);
  persistMarks();
  applyCardState(card, event);
  if (popupUid === event.uid) showPopup(event, card);
  $('#counter').textContent =
    `${main.querySelectorAll('.event:not(.hidden)').length} sichtbar · ${marks.size} markiert · ` +
    `${DATA.events.filter((e) => e.tags.length).length} getaggt`;
  if (state.onlyMarked) render();
});

/* ----------------------------------------------------------------- export */
function markedEvents() {
  return DATA.events
    .filter((event) => marks.has(event.uid))
    .sort((a, b) => (a.date.split('.').reverse().join('') + a.start)
      .localeCompare(b.date.split('.').reverse().join('') + b.start));
}

function asMarkdown(events) {
  if (!events.length) return '_keine Events markiert_';
  const lines = ['# ESE Kongress 2026 – meine Auswahl', ''];
  let day = null;
  events.forEach((event) => {
    if (event.day_id !== day) {
      day = event.day_id;
      lines.push('', `## ${event.weekday} ${event.date}`, '');
    }
    lines.push(`- **${event.start}–${event.end}** ${event.title}`);
    lines.push(`  - Raum: ${event.rooms.join(', ') || '—'}${event.topic ? ` · Thema: ${event.topic}` : ''}`);
    const speakers = [...new Set(event.papers.flatMap((paper) => paper.persons.map((person) => person.display)))];
    if (speakers.length) lines.push(`  - ${speakers.join(' · ')}`);
    if (event.tags.length) lines.push(`  - Highlights: ${event.tags.map((tag) => DATA.tag_definitions[tag].label).join(', ')}`);
    if (event.source_url) lines.push(`  - ${event.source_url}`);
  });
  return lines.join('\n');
}

function asIcs(events) {
  const stamp = (date, time) => {
    const [day, month, year] = date.split('.');
    return `${year}${month}${day}T${time.replace(':', '')}00`;
  };
  const escape = (value) => String(value).replace(/[\\;,]/g, '\\$&');
  const lines = ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//ese-kongress-local-copy//DE'];
  events.forEach((event) => {
    lines.push('BEGIN:VEVENT',
      `UID:${event.uid}@ese-kongress.local`,
      `DTSTART;TZID=Europe/Berlin:${stamp(event.date, event.start)}`,
      `DTEND;TZID=Europe/Berlin:${stamp(event.date, event.end)}`,
      `SUMMARY:${escape(event.title)}`,
      `LOCATION:${escape(event.rooms.join(', '))}`,
      `DESCRIPTION:${escape(event.topic || '') + (event.source_url ? '\\n' + escape(event.source_url) : '')}`,
      'END:VEVENT');
  });
  lines.push('END:VCALENDAR');
  return lines.join('\r\n');
}

const exportDialog = $('#export-dialog');
let exportFormat = 'markdown';

function renderExport() {
  const events = markedEvents();
  const text = exportFormat === 'markdown' ? asMarkdown(events)
    : exportFormat === 'ics' ? asIcs(events)
      : JSON.stringify({
        exported_at: new Date().toISOString(),
        marks: events.map((event) => ({
          uid: event.uid, date: event.date, start: event.start, end: event.end,
          title: event.title, rooms: event.rooms, topic: event.topic,
          tags: event.tags, source_url: event.source_url,
        })),
      }, null, 2);
  $('#export-text').value = text;
}

$('#export').onclick = () => { renderExport(); exportDialog.showModal(); };
$('#export-close').onclick = () => exportDialog.close();
$('#export-copy').onclick = () => navigator.clipboard.writeText($('#export-text').value);
$('#export-download').onclick = () => {
  const extension = exportFormat === 'markdown' ? 'md' : exportFormat === 'ics' ? 'ics' : 'json';
  const blob = new Blob([$('#export-text').value], { type: 'text/plain;charset=utf-8' });
  const link = el('a');
  link.href = URL.createObjectURL(blob);
  link.download = `ese2026-auswahl.${extension}`;
  link.click();
  URL.revokeObjectURL(link.href);
};
$('#export-import').onclick = () => {
  const raw = prompt('Markierungen einfügen (JSON-Export oder Liste von uids):');
  if (!raw) return;
  try {
    const parsed = JSON.parse(raw);
    const uids = Array.isArray(parsed) ? parsed : (parsed.marks || []).map((entry) => entry.uid || entry);
    uids.filter((uid) => byUid.has(uid)).forEach((uid) => marks.add(uid));
    persistMarks();
    renderExport();
    render();
  } catch (error) {
    alert(`Konnte die Eingabe nicht lesen: ${error.message}`);
  }
};
document.querySelectorAll('.export-tabs button').forEach((button) => {
  button.onclick = () => {
    exportFormat = button.dataset.format;
    document.querySelectorAll('.export-tabs button').forEach((other) => other.classList.toggle('active', other === button));
    renderExport();
  };
});

/* ------------------------------------------------------------- top bar UI */
function buildDayTabs() {
  const nav = $('#days');
  DATA.days.forEach((day) => {
    const button = el('button');
    button.textContent = day.weekday || day.date;
    button.appendChild(el('small', null, day.date));
    button.classList.toggle('active', day.id === state.day);
    button.onclick = () => {
      state.day = day.id;
      persistState();
      nav.querySelectorAll('button').forEach((other) => other.classList.toggle('active', other === button));
      render();
    };
    nav.appendChild(button);
  });
}

function buildTopicFilter() {
  const select = $('#topic-filter');
  Object.values(DATA.topics)
    .filter((topic) => topic.name)
    .forEach((topic) => {
      const option = el('option', null, topic.name);
      option.value = topic.name;
      select.appendChild(option);
    });
  select.value = state.topic;
  select.onchange = () => { state.topic = select.value; persistState(); render(); };
}

function bindControls() {
  const search = $('#search');
  search.value = state.query;
  let debounce = null;
  search.oninput = () => {
    clearTimeout(debounce);
    debounce = setTimeout(() => { state.query = search.value.trim(); persistState(); render(); }, 140);
  };

  [['#only-hits', 'onlyHits'], ['#only-marked', 'onlyMarked'], ['#include-weak', 'includeWeak']]
    .forEach(([selector, key]) => {
      const box = $(selector);
      box.checked = state[key];
      box.onchange = () => { state[key] = box.checked; persistState(); render(); };
    });

  document.querySelectorAll('#view-toggle button').forEach((button) => {
    button.classList.toggle('active', button.dataset.view === state.view);
    button.onclick = () => {
      state.view = button.dataset.view;
      persistState();
      document.querySelectorAll('#view-toggle button')
        .forEach((other) => other.classList.toggle('active', other.dataset.view === state.view));
      render();
    };
  });
}

buildDayTabs();
buildTopicFilter();
bindControls();
render();
