import type { LucideIcon } from 'lucide-react'
import {
  Anchor,
  Apple,
  Balloon,
  Bell,
  Bike,
  Bird,
  BookOpen,
  Bug,
  Camera,
  Carrot,
  Castle,
  Cat,
  CircleDot,
  Clock3,
  Cloud,
  Compass,
  CookingPot,
  Crosshair,
  Crown,
  CupSoda,
  Diamond,
  Dog,
  Drum,
  Fish,
  Flame,
  Flower2,
  Footprints,
  Gem,
  Glasses,
  Guitar,
  Hammer,
  Heart,
  House,
  KeyRound,
  Leaf,
  Magnet,
  Moon,
  Mountain,
  Music2,
  Nut,
  Pencil,
  Plane,
  Rocket,
  Sailboat,
  Shell,
  Snowflake,
  Star,
  Sun,
  TrainFront,
  TreePine,
  Turtle,
  Umbrella,
  WavesLadder,
  Zap,
} from 'lucide-react'

export const symbolIcons: Record<string, LucideIcon> = {
  bird: Bird,
  tree: TreePine,
  anchor: Anchor,
  target: Crosshair,
  cheese: CookingPot,
  stone: Gem,
  'ice-cube': Snowflake,
  igloo: House,
  carrot: Carrot,
  'treble-clef': Music2,
  star: Star,
  moon: Moon,
  sun: Sun,
  crown: Crown,
  key: KeyRound,
  apple: Apple,
  mushroom: CircleDot,
  flower: Flower2,
  fish: Fish,
  boat: Sailboat,
  bell: Bell,
  candle: Flame,
  heart: Heart,
  'lightning-bolt': Zap,
  umbrella: Umbrella,
  house: House,
  mountain: Mountain,
  leaf: Leaf,
  cup: CupSoda,
  clock: Clock3,
  ladder: WavesLadder,
  shell: Shell,
  balloon: Balloon,
  cat: Cat,
  dog: Dog,
  turtle: Turtle,
  butterfly: Bug,
  guitar: Guitar,
  drum: Drum,
  hammer: Hammer,
  magnet: Magnet,
  rocket: Rocket,
  airplane: Plane,
  train: TrainFront,
  bicycle: Bike,
  camera: Camera,
  book: BookOpen,
  pencil: Pencil,
  snowflake: Snowflake,
  castle: Castle,
  boot: Footprints,
  glasses: Glasses,
  diamond: Diamond,
  cloud: Cloud,
  acorn: Nut,
  ladybird: Bug,
  compass: Compass,
}
