import os
import sys
import argparse

def find_files(directory, extensions):
    """Recursively finds files with the given extensions in the directory."""
    matches = []
    for root, _, files in os.walk(directory):
        for file in files:
            if any(file.endswith(ext) for ext in extensions):
                matches.append(os.path.join(root, file))
    return matches

def main():
    # Set up argument parser
    parser = argparse.ArgumentParser(description="Search for files by extension.")
    parser.add_argument("--path", help="Directory path to search in.", type=str)
    parser.add_argument("--type", help="Comma-separated file extensions to search for.", type=str)

    # Parse arguments
    args = parser.parse_args()

    # Validate arguments
    if not args.path or not args.type:
        parser.print_help()
        sys.exit(1)

    # Validate the path
    if not os.path.isdir(args.path):
        print(f"Error: The path '{args.path}' is not a valid directory.")
        sys.exit(1)

    # Parse extensions and ensure they're in the correct format
    extensions = args.type.split(",")
    extensions = [f".{ext.lstrip('.')}" for ext in extensions]  # Ensure leading dot

    # Find and print the matching files
    matching_files = find_files(args.path, extensions)
    for file in matching_files:
        print(file)

if __name__ == "__main__":
    main()

# call by:
# $ python codeOxygenator.py --path=test/ --type=cpp,h
# test/autoGeneratedUncommentedCppCode/main.cpp
# test/autoGeneratedUncommentedCppCode/Book.h
# test/autoGeneratedUncommentedCppCode/LibrarySystem.h
# test/autoGeneratedUncommentedCppCode/LibrarySystem.cpp
# test/autoGeneratedUncommentedCppCode/Book.cpp
# test/autoGeneratedUncommentedCppCode/Library.cpp
# test/autoGeneratedUncommentedCppCode/Library.h
