set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(WINDOWS_MINGW_TRIPLET "$ENV{WINDOWS_MINGW_TRIPLET}")
if(NOT WINDOWS_MINGW_TRIPLET)
    set(WINDOWS_MINGW_TRIPLET "x86_64-w64-mingw32")
endif()

set(WINDOWS_QT_PREFIX "$ENV{WINDOWS_QT_PREFIX}")
if(NOT WINDOWS_QT_PREFIX AND DEFINED ENV{MXE_PREFIX})
    set(WINDOWS_QT_PREFIX "$ENV{MXE_PREFIX}/usr/${WINDOWS_MINGW_TRIPLET}/qt5")
endif()

if(DEFINED ENV{WINDOWS_MINGW_BIN})
    set(CMAKE_C_COMPILER "$ENV{WINDOWS_MINGW_BIN}/${WINDOWS_MINGW_TRIPLET}-gcc")
    set(CMAKE_CXX_COMPILER "$ENV{WINDOWS_MINGW_BIN}/${WINDOWS_MINGW_TRIPLET}-g++")
    set(CMAKE_RC_COMPILER "$ENV{WINDOWS_MINGW_BIN}/${WINDOWS_MINGW_TRIPLET}-windres")
else()
    set(CMAKE_C_COMPILER "${WINDOWS_MINGW_TRIPLET}-gcc")
    set(CMAKE_CXX_COMPILER "${WINDOWS_MINGW_TRIPLET}-g++")
    set(CMAKE_RC_COMPILER "${WINDOWS_MINGW_TRIPLET}-windres")
endif()

if(WINDOWS_QT_PREFIX)
    list(APPEND CMAKE_PREFIX_PATH "${WINDOWS_QT_PREFIX}")
    list(APPEND CMAKE_FIND_ROOT_PATH "${WINDOWS_QT_PREFIX}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_CROSSCOMPILING_EMULATOR wine)
